# Generated by Django 4.0 on 2021-12-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
